--El número se asigna automaticamente
--Familia

CREATE OR REPLACE TRIGGER T1_FAMILIA
BEFORE INSERT ON FAMILIAS
FOR EACH ROW
DECLARE
valorNumero INTEGER;
BEGIN 
    SELECT COUNT(*)+1 INTO valorNumero FROM FAMILIAS;
    :new.numero := valorNumero;
END;

--Personas
CREATE OR REPLACE TRIGGER T1_PERSONAS
BEFORE INSERT ON PERSONAS
FOR EACH ROW
DECLARE
valorNumero INTEGER;
BEGIN 
    SELECT COUNT(*)+1 INTO valorNumero FROM PERSONAS;
    :new.numero := valorNumero;
END;

--Asignaciones
CREATE OR REPLACE TRIGGER T1_Asignaciones
BEFORE INSERT ON ASIGNACIONES
FOR EACH ROW
DECLARE
valorNumero INTEGER;
BEGIN 
    SELECT COUNT(*)+1 INTO valorNumero FROM ASIGNACIONES;
    :new.numero := valorNumero;
END;

--Opiniones
CREATE OR REPLACE TRIGGER T1_Opiniones
BEFORE INSERT ON OPINIONES
FOR EACH ROW
DECLARE
valorNumero INTEGER;
BEGIN 
    SELECT COUNT(*)+1 INTO valorNumero FROM ASIGNACIONES;
    :new.numero := valorNumero;
END;

--TRIGGER FECHA

--ASIGNACION FECHA 
CREATE OR REPLACE TRIGGER T2_ASIGNACIONES
BEFORE INSERT ON ASIGNACIONES
FOR EACH ROW 
BEGIN  
    :new.fecha:=SYSDATE;
END;

--OPINIONES FECHA
CREATE OR REPLACE TRIGGER T1_OPINIONES
BEFORE INSERT ON OPINIONES
FOR EACH ROW 
BEGIN  
    :new.fecha:=SYSDATE;
END;
