ALTER TABLE ASIGNACIONES
ADD CONSTRAINT PK_asignaciones PRIMARY KEY (numero);
ALTER TABLE BIENESASIGNADOS
ADD CONSTRAINT PK_idUBienesAsi PRIMARY KEY(numero,bien);
ALTER TABLE BIENES
ADD CONSTRAINT PK_idBienes PRIMARY KEY(codigo);
ALTER TABLE FAMILIAS
ADD CONSTRAINT PK_Familias PRIMARY KEY(numero);
ALTER TABLE BIENESFAMILIAS
ADD CONSTRAINT PK_idPremium PRIMARY KEY(numero,codigo);
ALTER TABLE PERSONAS
ADD CONSTRAINT PK_idPrestige PRIMARY KEY(codigo);
ALTER TABLE OPINIONES
ADD CONSTRAINT PK_idElite PRIMARY KEY(numero);
ALTER TABLE OPINIONESGRUPALES
ADD CONSTRAINT PK_Pagos PRIMARY KEY(numero);

ALTER TABLE PERSONAS
ADD CONSTRAINT UK_Personas UNIQUE (numeroF);
ALTER TABLE OPINIONES
ADD CONSTRAINT UK_Opiniones UNIQUE (justificacion);

ALTER TABLE ASIGNACIONES
ADD CONSTRAINT FK1_asigna FOREIGN KEY(numeroF) REFERENCES FAMILIAS(numero);
ALTER TABLE BIENESASIGNADOS
ADD CONSTRAINT FK1_BIENESASIGNADOS FOREIGN KEY(numero) REFERENCES ASIGNACIONES(numero);
ALTER TABLE BIENESASIGNADOS
ADD CONSTRAINT FK2_BIENESASIGNADOS FOREIGN KEY(bien) REFERENCES BIENES(codigo);
ALTER TABLE BIENES
ADD CONSTRAINT FK1_Bienes FOREIGN KEY(numeroO) REFERENCES OPINIONES(numero);
ALTER TABLE BIENESFAMILIAS
ADD CONSTRAINT FK1_BIENESFAMILIAS FOREIGN KEY(numero) REFERENCES FAMILIAS(numero);
ALTER TABLE BIENESFAMILIAS
ADD CONSTRAINT FK2_BIENESFAMILIAS FOREIGN KEY(codigo) REFERENCES BIENES(codigo);
ALTER TABLE PERSONAS
ADD CONSTRAINT FK1_Personas FOREIGN KEY(numero) REFERENCES FAMILIAS(numero);
ALTER TABLE OPINIONES
ADD CONSTRAINT FK1_OPINIONES FOREIGN KEY(codigoP) REFERENCES PERSONAS(codigo);
ALTER TABLE OPINIONESGRUPALES 
ADD CONSTRAINT FK1_OPINIONESGRUPALES FOREIGN KEY(numero) REFERENCES OPINIONES(numero);
